//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine_Presentador.M9 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoPresentadorM9 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoPresentadorM9() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine_Presentador.M9.RecursoPresentadorM9", typeof(RecursoPresentadorM9).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;input-group&quot;&gt;&lt;div class=&quot;input-group-addon&quot;&gt;&lt;i class=&quot;fa fa-calendar&quot;&gt;&lt;/i&gt;&lt;/div&gt;&lt;input type=&quot;text&quot; class=&quot;form-control pull-right&quot; id=&quot;reservation&quot; placeholder=&quot;.
        /// </summary>
        internal static string AbrirFecha {
            get {
                return ResourceManager.GetString("AbrirFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;input_cliente&quot; class=&quot;form-control&quot; id=&quot;cliente_id&quot; placeholder=&quot;.
        /// </summary>
        internal static string AbrirNombreCliente {
            get {
                return ResourceManager.GetString("AbrirNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span .
        /// </summary>
        internal static string AbrirSpan {
            get {
                return ResourceManager.GetString("AbrirSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string AbrirTD {
            get {
                return ResourceManager.GetString("AbrirTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string AbrirTR {
            get {
                return ResourceManager.GetString("AbrirTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrónimo:.
        /// </summary>
        internal static string Acronimo {
            get {
                return ResourceManager.GetString("Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;text-align: center;&quot;&gt;&lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; type=&quot;submit&quot; runat=&quot;server&quot; href=&quot;FacturasPorPagar.aspx&quot;&gt;&lt;/a&gt;&lt;/th&gt;.
        /// </summary>
        internal static string aja {
            get {
                return ResourceManager.GetString("aja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string alertaError {
            get {
                return ResourceManager.GetString("alertaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string alertaHtml {
            get {
                return ResourceManager.GetString("alertaHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string alertaHtmlFinal {
            get {
                return ResourceManager.GetString("alertaHtmlFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-dismissible.
        /// </summary>
        internal static string alertaSuccess {
            get {
                return ResourceManager.GetString("alertaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string alertClase1 {
            get {
                return ResourceManager.GetString("alertClase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string alertRole1 {
            get {
                return ResourceManager.GetString("alertRole1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;text-align: center;&quot;&gt;&lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; type=&quot;submit&quot; runat=&quot;server&quot; href=&quot;FacturasPorPagar.aspx?id=.
        /// </summary>
        internal static string boton {
            get {
                return ResourceManager.GetString("boton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a style=&apos;margin-left:5px;&apos; class=&apos;btn btn-danger glyphicon glyphicon-remove-circle&apos; href=&quot;ConsultarContactos.aspx?idCont=.
        /// </summary>
        internal static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  class=&quot;btn btn-danger glyphicon glyphicon-remove-circle&quot; href=&quot;M14_ConsultarPlanillasSolicitadas.aspx?idEliminar=.
        /// </summary>
        internal static string BotonEliminarSolicitud {
            get {
                return ResourceManager.GetString("BotonEliminarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Habilitar&quot;  class=&quot;btn btn-success glyphicon glyphicon-ok&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonHab {
            get {
                return ResourceManager.GetString("BotonHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInfo {
            get {
                return ResourceManager.GetString("BotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Inhabilitar&quot; class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; &gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInhab {
            get {
                return ResourceManager.GetString("BotonInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Involucrados&quot; class=&quot;btn btn-info glyphicon glyphicon-user&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInvol {
            get {
                return ResourceManager.GetString("BotonInvol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Modificar&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModalE&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonModif {
            get {
                return ResourceManager.GetString("BotonModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;text-align: center;&quot;&gt;&lt;a class=&quot;btn btn-primary glyphicon glyphicon-check&quot; type=&quot;submit&quot; runat=&quot;server&quot; href=&quot;CargarPago1.aspx?id=.
        /// </summary>
        internal static string botonPagarAbrir {
            get {
                return ResourceManager.GetString("botonPagarAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string CloseDiv {
            get {
                return ResourceManager.GetString("CloseDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h3&gt;.
        /// </summary>
        internal static string Closeh3 {
            get {
                return ResourceManager.GetString("Closeh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h4&gt;.
        /// </summary>
        internal static string Closeh4 {
            get {
                return ResourceManager.GetString("Closeh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CloseTD {
            get {
                return ResourceManager.GetString("CloseTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTR {
            get {
                return ResourceManager.GetString("CloseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Coma {
            get {
                return ResourceManager.GetString("Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Coma1 {
            get {
                return ResourceManager.GetString("Coma1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp.
        /// </summary>
        internal static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label for=&quot;input_cliente&quot;&gt;Cliente (compañía contratante)&lt;/label&gt;.
        /// </summary>
        internal static string EtiquetaCliente {
            get {
                return ResourceManager.GetString("EtiquetaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class=&quot;label label-danger&quot;&gt; Deshabilitada .
        /// </summary>
        internal static string EtiquetaDeshabilitada {
            get {
                return ResourceManager.GetString("EtiquetaDeshabilitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label&gt;Fecha factura&lt;/label&gt;.
        /// </summary>
        internal static string EtiquetaFecha {
            get {
                return ResourceManager.GetString("EtiquetaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class=&quot;label label-success&quot;&gt; Habilitada .
        /// </summary>
        internal static string EtiquetaHabilitada {
            get {
                return ResourceManager.GetString("EtiquetaHabilitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;&lt;span class=&quot;label label-success&quot;&gt;Pagada&lt;/span&gt;&lt;/td&gt;.
        /// </summary>
        internal static string EtiquetaPagada {
            get {
                return ResourceManager.GetString("EtiquetaPagada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;&lt;span class=&quot;label label-warning&quot;&gt;Por pagar&lt;/span&gt;&lt;/td&gt;.
        /// </summary>
        internal static string EtiquetaPorPagar {
            get {
                return ResourceManager.GetString("EtiquetaPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha:.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-danger&quot;&gt;Inhabilitada&lt;/span&gt;.
        /// </summary>
        internal static string inhabilitado {
            get {
                return ResourceManager.GetString("inhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.3.
        /// </summary>
        internal static string interfazRCi {
            get {
                return ResourceManager.GetString("interfazRCi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1.
        /// </summary>
        internal static string interfazRH {
            get {
                return ResourceManager.GetString("interfazRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar:.
        /// </summary>
        internal static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Mod8 {
            get {
                return ResourceManager.GetString("Mod8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        internal static string Nombre1 {
            get {
                return ResourceManager.GetString("Nombre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Modificar&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; style=&quot;margin-left 0.2px&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModalE&quot; id=&quot;Edi.
        /// </summary>
        internal static string OpenBotonEdit {
            get {
                return ResourceManager.GetString("OpenBotonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Habilitar&quot;  class=&quot;btn btn-success glyphicon glyphicon-ok&quot; style=&quot;margin-left 0.2px&quot; id=&quot;Hab.
        /// </summary>
        internal static string OpenBotonHab {
            get {
                return ResourceManager.GetString("OpenBotonHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; style=&quot;margin-left 0.2px&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot; OnClick=&quot;MostrarInfo&quot; id=&quot;Inf.
        /// </summary>
        internal static string OpenBotonInfo {
            get {
                return ResourceManager.GetString("OpenBotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Inhabilitar&quot; class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; style=&quot;margin-left 0.2px&quot; id=&quot;Inh.
        /// </summary>
        internal static string OpenBotonInhab {
            get {
                return ResourceManager.GetString("OpenBotonInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;.
        /// </summary>
        internal static string OpenDivRow {
            get {
                return ResourceManager.GetString("OpenDivRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 style=&quot;bold&quot;&gt;.
        /// </summary>
        internal static string Openh3 {
            get {
                return ResourceManager.GetString("Openh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;.
        /// </summary>
        internal static string Openh4 {
            get {
                return ResourceManager.GetString("Openh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string OpenTR {
            get {
                return ResourceManager.GetString("OpenTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;idComp=.
        /// </summary>
        internal static string ParametroIdComp {
            get {
                return ResourceManager.GetString("ParametroIdComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Modulo8/interfazRestriccionesAvanceCinta.aspx?succes=true.
        /// </summary>
        internal static string ReturnRestCinta {
            get {
                return ResourceManager.GetString("ReturnRestCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIF:.
        /// </summary>
        internal static string Rif {
            get {
                return ResourceManager.GetString("Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono:.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string tipoAlerta {
            get {
                return ResourceManager.GetString("tipoAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&quot;btnaceptar&quot; style=&quot;margin-top:5%&quot; class=&quot;btn btn-primary&quot;  type=&quot;submit&quot; runat=&quot;server&quot; href=&quot;AgregarContacto.aspx?typeComp=.
        /// </summary>
        internal static string VentanaAgregarContacto {
            get {
                return ResourceManager.GetString("VentanaAgregarContacto", resourceCulture);
            }
        }
    }
}
