//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTangerine.DAO.M2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUser() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTangerine.DAO.M2.ResourceUser", typeof(ResourceUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_AgregarUsuario.
        /// </summary>
        internal static string AgregarUsuario {
            get {
                return ResourceManager.GetString("AgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_BorrarUsuario.
        /// </summary>
        internal static string BorrarUsuario {
            get {
                return ResourceManager.GetString("BorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_id.
        /// </summary>
        internal static string ComIDUser {
            get {
                return ResourceManager.GetString("ComIDUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ConsultarIdUltimoUsuario.
        /// </summary>
        internal static string ConsultLastUserID {
            get {
                return ResourceManager.GetString("ConsultLastUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ConsultarUsuario.
        /// </summary>
        internal static string ConsultUser {
            get {
                return ResourceManager.GetString("ConsultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ModificarContraUsuario.
        /// </summary>
        internal static string ModificarContraUsuario {
            get {
                return ResourceManager.GetString("ModificarContraUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ModificarRolUsuario.
        /// </summary>
        internal static string ModificarRolUsuario {
            get {
                return ResourceManager.GetString("ModificarRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ObtenerDatoUsuario.
        /// </summary>
        internal static string ObtenerDatoUsuario {
            get {
                return ResourceManager.GetString("ObtenerDatoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ObtenerOpciones.
        /// </summary>
        internal static string ObtenerOpciones {
            get {
                return ResourceManager.GetString("ObtenerOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ObtenerRolUsuario.
        /// </summary>
        internal static string ObtenerRolUsuario {
            get {
                return ResourceManager.GetString("ObtenerRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ObtenerRolUsuarioPorNombre.
        /// </summary>
        internal static string ObtenerRolUsuarioPorNombre {
            get {
                return ResourceManager.GetString("ObtenerRolUsuarioPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_ObtenerUsuarioDeEmpleado.
        /// </summary>
        internal static string ObtenerUsuarioDeEmpleado {
            get {
                return ResourceManager.GetString("ObtenerUsuarioDeEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a opc_nombre.
        /// </summary>
        internal static string OpcNombre {
            get {
                return ResourceManager.GetString("OpcNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a opc_url.
        /// </summary>
        internal static string OpcUrl {
            get {
                return ResourceManager.GetString("OpcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @contraseña.
        /// </summary>
        internal static string ParametroContrasenia {
            get {
                return ResourceManager.GetString("ParametroContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @contraseña_nueva.
        /// </summary>
        internal static string ParametroContraseniaNueva {
            get {
                return ResourceManager.GetString("ParametroContraseniaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fecha_creacion.
        /// </summary>
        internal static string ParametroFechaCreacion {
            get {
                return ResourceManager.GetString("ParametroFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @id.
        /// </summary>
        internal static string ParametroID {
            get {
                return ResourceManager.GetString("ParametroID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @menu_nom.
        /// </summary>
        internal static string ParametroMenuNombre {
            get {
                return ResourceManager.GetString("ParametroMenuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @emp_num_ficha.
        /// </summary>
        internal static string ParametroNumFicha {
            get {
                return ResourceManager.GetString("ParametroNumFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @codigo_rol.
        /// </summary>
        internal static string ParametroRolCodigo {
            get {
                return ResourceManager.GetString("ParametroRolCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rol_nombre.
        /// </summary>
        internal static string ParametroRolNombre {
            get {
                return ResourceManager.GetString("ParametroRolNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rol_nombre_nuevo.
        /// </summary>
        internal static string ParametroRolUsuario {
            get {
                return ResourceManager.GetString("ParametroRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usuario.
        /// </summary>
        internal static string ParametroUsuario {
            get {
                return ResourceManager.GetString("ParametroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_id.
        /// </summary>
        internal static string ParametroUsuID {
            get {
                return ResourceManager.GetString("ParametroUsuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rol_id.
        /// </summary>
        internal static string RolId {
            get {
                return ResourceManager.GetString("RolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a men_nombre.
        /// </summary>
        internal static string RolMenu {
            get {
                return ResourceManager.GetString("RolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rol_nombre.
        /// </summary>
        internal static string RolNombre {
            get {
                return ResourceManager.GetString("RolNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_activo.
        /// </summary>
        internal static string UsuActivo {
            get {
                return ResourceManager.GetString("UsuActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_contrasena.
        /// </summary>
        internal static string UsuContrasena {
            get {
                return ResourceManager.GetString("UsuContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_emp_num_ficha.
        /// </summary>
        internal static string UsuEmpFicha {
            get {
                return ResourceManager.GetString("UsuEmpFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_fecha_creacion.
        /// </summary>
        internal static string UsuFechaCreacion {
            get {
                return ResourceManager.GetString("UsuFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_rol_id.
        /// </summary>
        internal static string UsuFKRol {
            get {
                return ResourceManager.GetString("UsuFKRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_usuario.
        /// </summary>
        internal static string UsuNombre {
            get {
                return ResourceManager.GetString("UsuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_VerificarExistenciaUsuario.
        /// </summary>
        internal static string VerificarExistenciaUsuario {
            get {
                return ResourceManager.GetString("VerificarExistenciaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M2_VerificarUsuarioPorFichaEmpleado.
        /// </summary>
        internal static string VerificarUsuarioPorFichaEmpleado {
            get {
                return ResourceManager.GetString("VerificarUsuarioPorFichaEmpleado", resourceCulture);
            }
        }
    }
}
