//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTangerine.DAO.M2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTangerine.DAO.M2.ResourceUser", typeof(ResourceUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_AgregarUsuario.
        /// </summary>
        internal static string AgregarUsuario {
            get {
                return ResourceManager.GetString("AgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ModificarContraUsuario.
        /// </summary>
        internal static string ModificarContraUsuario {
            get {
                return ResourceManager.GetString("ModificarContraUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ModificarRolUsuario.
        /// </summary>
        internal static string ModificarRolUsuario {
            get {
                return ResourceManager.GetString("ModificarRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ObtenerDatoUsuario.
        /// </summary>
        internal static string ObtenerDatoUsuario {
            get {
                return ResourceManager.GetString("ObtenerDatoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ObtenerOpciones.
        /// </summary>
        internal static string ObtenerOpciones {
            get {
                return ResourceManager.GetString("ObtenerOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ObtenerRolUsuario.
        /// </summary>
        internal static string ObtenerRolUsuario {
            get {
                return ResourceManager.GetString("ObtenerRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ObtenerRolUsuarioPorNombre.
        /// </summary>
        internal static string ObtenerRolUsuarioPorNombre {
            get {
                return ResourceManager.GetString("ObtenerRolUsuarioPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_ObtenerUsuarioDeEmpleado.
        /// </summary>
        internal static string ObtenerUsuarioDeEmpleado {
            get {
                return ResourceManager.GetString("ObtenerUsuarioDeEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opc_nombre.
        /// </summary>
        internal static string OpcNombre {
            get {
                return ResourceManager.GetString("OpcNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opc_url.
        /// </summary>
        internal static string OpcUrl {
            get {
                return ResourceManager.GetString("OpcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @contraseña.
        /// </summary>
        internal static string ParametroContrasenia {
            get {
                return ResourceManager.GetString("ParametroContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @contraseña_nueva.
        /// </summary>
        internal static string ParametroContraseniaNueva {
            get {
                return ResourceManager.GetString("ParametroContraseniaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_creacion.
        /// </summary>
        internal static string ParametroFechaCreacion {
            get {
                return ResourceManager.GetString("ParametroFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @menu_nom.
        /// </summary>
        internal static string ParametroMenuNombre {
            get {
                return ResourceManager.GetString("ParametroMenuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emp_num_ficha.
        /// </summary>
        internal static string ParametroNumFicha {
            get {
                return ResourceManager.GetString("ParametroNumFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @codigo_rol.
        /// </summary>
        internal static string ParametroRolCodigo {
            get {
                return ResourceManager.GetString("ParametroRolCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rol_nombre.
        /// </summary>
        internal static string ParametroRolNombre {
            get {
                return ResourceManager.GetString("ParametroRolNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rol_nombre_nuevo.
        /// </summary>
        internal static string ParametroRolUsuario {
            get {
                return ResourceManager.GetString("ParametroRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usuario.
        /// </summary>
        internal static string ParametroUsuario {
            get {
                return ResourceManager.GetString("ParametroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rol_id.
        /// </summary>
        internal static string RolId {
            get {
                return ResourceManager.GetString("RolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men_nombre.
        /// </summary>
        internal static string RolMenu {
            get {
                return ResourceManager.GetString("RolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rol_nombre.
        /// </summary>
        internal static string RolNombre {
            get {
                return ResourceManager.GetString("RolNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_activo.
        /// </summary>
        internal static string UsuActivo {
            get {
                return ResourceManager.GetString("UsuActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_emp_num_ficha.
        /// </summary>
        internal static string UsuEmpFicha {
            get {
                return ResourceManager.GetString("UsuEmpFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_fecha_creacion.
        /// </summary>
        internal static string UsuFechaCreacion {
            get {
                return ResourceManager.GetString("UsuFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_rol_id.
        /// </summary>
        internal static string UsuFKRol {
            get {
                return ResourceManager.GetString("UsuFKRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_usuario.
        /// </summary>
        internal static string UsuNombre {
            get {
                return ResourceManager.GetString("UsuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_VerificarExistenciaUsuario.
        /// </summary>
        internal static string VerificarExistenciaUsuario {
            get {
                return ResourceManager.GetString("VerificarExistenciaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2_VerificarUsuarioPorFichaEmpleado.
        /// </summary>
        internal static string VerificarUsuarioPorFichaEmpleado {
            get {
                return ResourceManager.GetString("VerificarUsuarioPorFichaEmpleado", resourceCulture);
            }
        }
    }
}
