//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine_Presentador.M6 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPresentadorPropuesta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPresentadorPropuesta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine_Presentador.M6.RecursosPresentadorPropuesta", typeof(RecursosPresentadorPropuesta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string AbrirTD {
            get {
                return ResourceManager.GetString("AbrirTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;text-align:center;&quot;&gt;.
        /// </summary>
        internal static string AbrirTD2 {
            get {
                return ResourceManager.GetString("AbrirTD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string AbrirTR {
            get {
                return ResourceManager.GetString("AbrirTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string AlertDanger {
            get {
                return ResourceManager.GetString("AlertDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string AlertShowSu1 {
            get {
                return ResourceManager.GetString("AlertShowSu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string AlertShowSu2 {
            get {
                return ResourceManager.GetString("AlertShowSu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-dismissible.
        /// </summary>
        internal static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-success&quot;&gt;Aprobado&lt;/span&gt;.
        /// </summary>
        internal static string aprobado {
            get {
                return ResourceManager.GetString("aprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;glyphicon glyphicon-bitcoin&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string bitcoin {
            get {
                return ResourceManager.GetString("bitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b style=&quot;color: #3c8dbc;&quot;&gt;Bf &lt;/b&gt;.
        /// </summary>
        internal static string bolivar {
            get {
                return ResourceManager.GetString("bolivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;&lt;/th&gt;.
        /// </summary>
        internal static string boton_cerrar_id {
            get {
                return ResourceManager.GetString("boton_cerrar_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string botonCerra {
            get {
                return ResourceManager.GetString("botonCerra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; type=&quot;submit&quot; runat=&quot;server&quot; style=&quot;margin-left:3px;&quot;  href=&quot;InformacionPropuesta.aspx?id=.
        /// </summary>
        internal static string botonConsultar {
            get {
                return ResourceManager.GetString("botonConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; type=&quot;submit&quot; runat=&quot;server&quot; style=&quot;margin-left:3px;&quot;   href=&quot;ModificarPropuesta.aspx?id=.
        /// </summary>
        internal static string botonEliminar {
            get {
                return ResourceManager.GetString("botonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; type=&quot;submit&quot; runat=&quot;server&quot; style=&quot;margin-left:3px;&quot;  href=&quot;ModificarPropuesta.aspx?id=.
        /// </summary>
        internal static string botonModificar {
            get {
                return ResourceManager.GetString("botonModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; type=&quot;button&quot; runat=&quot;server&quot; style=&quot;margin-left:3px;&quot;  onclick=&quot;return confirm(&apos;¿Esta seguro de que quiere eliminar este requerimiento?\n\nUna vez eliminado no podra recuperarlo.&apos;)&quot; href=&quot;ModificarPropuesta.aspx?idReq=.
        /// </summary>
        internal static string btn_Oeliminar {
            get {
                return ResourceManager.GetString("btn_Oeliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; type=&quot;submit&quot; runat=&quot;server&quot; style=&quot;margin-left:3px;&quot;  href=&quot;ModificarRequerimiento.aspx?idReq=.
        /// </summary>
        internal static string btn_OModificar {
            get {
                return ResourceManager.GetString("btn_OModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-danger&quot;&gt;Cerrado&lt;/span&gt;.
        /// </summary>
        internal static string cerrado {
            get {
                return ResourceManager.GetString("cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CerrarTD {
            get {
                return ResourceManager.GetString("CerrarTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarTR {
            get {
                return ResourceManager.GetString("CerrarTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;glyphicon glyphicon-usd&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string dolar {
            get {
                return ResourceManager.GetString("dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;glyphicon glyphicon-euro&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string euro {
            get {
                return ResourceManager.GetString("euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;idPro=.
        /// </summary>
        internal static string intermedioBoton {
            get {
                return ResourceManager.GetString("intermedioBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;id=.
        /// </summary>
        internal static string intermedioBoton2 {
            get {
                return ResourceManager.GetString("intermedioBoton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;idReq=0.
        /// </summary>
        internal static string intermedioBoton3 {
            get {
                return ResourceManager.GetString("intermedioBoton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-warning&quot;&gt;Pendiente&lt;/span&gt;.
        /// </summary>
        internal static string pendiente {
            get {
                return ResourceManager.GetString("pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;.
        /// </summary>
        internal static string Salto {
            get {
                return ResourceManager.GetString("Salto", resourceCulture);
            }
        }
    }
}
