//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine_Presentador.M7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoPresentadorM7 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoPresentadorM7() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine_Presentador.M7.RecursoPresentadorM7", typeof(RecursoPresentadorM7).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string alertaError {
            get {
                return ResourceManager.GetString("alertaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string alertaHtml {
            get {
                return ResourceManager.GetString("alertaHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string alertaHtmlFinal {
            get {
                return ResourceManager.GetString("alertaHtmlFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-dismissible.
        /// </summary>
        internal static string alertaModificado {
            get {
                return ResourceManager.GetString("alertaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;glyphicon glyphicon-bitcoin&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string bitcoin {
            get {
                return ResourceManager.GetString("bitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b style=&quot;color: #3c8dbc;&quot;&gt;Bf &lt;/b&gt;.
        /// </summary>
        internal static string bolivar {
            get {
                return ResourceManager.GetString("bolivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInfo {
            get {
                return ResourceManager.GetString("BotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-info glyphicon glyphicon-user&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonPersonal {
            get {
                return ResourceManager.GetString("BotonPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-danger&quot;&gt;Cancelado&lt;/span&gt;.
        /// </summary>
        internal static string Cancelado {
            get {
                return ResourceManager.GetString("Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente.
        /// </summary>
        internal static string CargoGerente {
            get {
                return ResourceManager.GetString("CargoGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programador.
        /// </summary>
        internal static string CargoProgramador {
            get {
                return ResourceManager.GetString("CargoProgramador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBoton {
            get {
                return ResourceManager.GetString("CloseBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonParametro {
            get {
                return ResourceManager.GetString("CloseBotonParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string CloseDiv {
            get {
                return ResourceManager.GetString("CloseDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CloseTd {
            get {
                return ResourceManager.GetString("CloseTd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/th&gt;.
        /// </summary>
        internal static string CloseTh {
            get {
                return ResourceManager.GetString("CloseTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTr {
            get {
                return ResourceManager.GetString("CloseTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo:.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CodMsjAgregado {
            get {
                return ResourceManager.GetString("CodMsjAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CodMsjError {
            get {
                return ResourceManager.GetString("CodMsjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CodMsjModificado {
            get {
                return ResourceManager.GetString("CodMsjModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-success&quot;&gt;Completado&lt;/span&gt;.
        /// </summary>
        internal static string Completado {
            get {
                return ResourceManager.GetString("Completado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-warning&quot;&gt;Completado a destiempo&lt;/span&gt;.
        /// </summary>
        internal static string CompletadoAdestiempo {
            get {
                return ResourceManager.GetString("CompletadoAdestiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM&apos;/&apos;dd&apos;/&apos;yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string DateFormat2 {
            get {
                return ResourceManager.GetString("DateFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-primary&quot;&gt;En Desarrollo&lt;/span&gt;.
        /// </summary>
        internal static string Desarrollo {
            get {
                return ResourceManager.GetString("Desarrollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;glyphicon glyphicon-usd&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string dolar {
            get {
                return ResourceManager.GetString("dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un empleado.
        /// </summary>
        internal static string ErrorEmpleadoVacio {
            get {
                return ResourceManager.GetString("ErrorEmpleadoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El proyecto no puede empezar antes de la fecha propuesta..
        /// </summary>
        internal static string ErrorFechaInicio {
            get {
                return ResourceManager.GetString("ErrorFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una fecha fin para el proyecto.
        /// </summary>
        internal static string ErrorFFinVacio {
            get {
                return ResourceManager.GetString("ErrorFFinVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Rango de fechas inválido. Fecha Fin debe ser mayor a Fecha Inicio..
        /// </summary>
        internal static string ErrorRangoFechas {
            get {
                return ResourceManager.GetString("ErrorRangoFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus:.
        /// </summary>
        internal static string Estatus {
            get {
                return ResourceManager.GetString("Estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        internal static string EstatusCancelado {
            get {
                return ResourceManager.GetString("EstatusCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado.
        /// </summary>
        internal static string EstatusCompletado {
            get {
                return ResourceManager.GetString("EstatusCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado a destiempo.
        /// </summary>
        internal static string EstatusCompletadoDestiempo {
            get {
                return ResourceManager.GetString("EstatusCompletadoDestiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En desarrollo.
        /// </summary>
        internal static string EstatusDesarrollo {
            get {
                return ResourceManager.GetString("EstatusDesarrollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;glyphicon glyphicon-euro&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string euro {
            get {
                return ResourceManager.GetString("euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaFin:.
        /// </summary>
        internal static string FechaEstimadaCulminar {
            get {
                return ResourceManager.GetString("FechaEstimadaCulminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaInicio:.
        /// </summary>
        internal static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M7IdEvento.
        /// </summary>
        internal static string IdEvento {
            get {
                return ResourceManager.GetString("IdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;IdProyecto=.
        /// </summary>
        internal static string idProyecto {
            get {
                return ResourceManager.GetString("idProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin.
        /// </summary>
        internal static string MonedaBitCoin {
            get {
                return ResourceManager.GetString("MonedaBitCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivar.
        /// </summary>
        internal static string MonedaBolivar {
            get {
                return ResourceManager.GetString("MonedaBolivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolar.
        /// </summary>
        internal static string MonedaDolar {
            get {
                return ResourceManager.GetString("MonedaDolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string MonedaEuro {
            get {
                return ResourceManager.GetString("MonedaEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Monto=.
        /// </summary>
        internal static string Monto {
            get {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto ha sido agregado.
        /// </summary>
        internal static string MsjAgregado {
            get {
                return ResourceManager.GetString("MsjAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        internal static string MsjError {
            get {
                return ResourceManager.GetString("MsjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Por favor vuelva a intentarlo.
        /// </summary>
        internal static string MsjErrorGenerico {
            get {
                return ResourceManager.GetString("MsjErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto ha sido modificado.
        /// </summary>
        internal static string MsjModificado {
            get {
                return ResourceManager.GetString("MsjModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        internal static string NombreProyecto {
            get {
                return ResourceManager.GetString("NombreProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; href=&quot;InformacionProyecto.aspx?idCont=.
        /// </summary>
        internal static string OpenBotonInfo {
            get {
                return ResourceManager.GetString("OpenBotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Modificar&quot;  class=&quot;btn btn-default glyphicon glyphicon-pencil&quot; href=&quot;modificarProyecto.aspx?idCont=.
        /// </summary>
        internal static string OpenBotonModificar {
            get {
                return ResourceManager.GetString("OpenBotonModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-info glyphicon glyphicon-user&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot; OnClick=&quot;MostrarPersonal&quot; id=&quot;Personal&quot;.
        /// </summary>
        internal static string OpenBotonPersonal {
            get {
                return ResourceManager.GetString("OpenBotonPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;.
        /// </summary>
        internal static string OpenDiv {
            get {
                return ResourceManager.GetString("OpenDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;.
        /// </summary>
        internal static string OpenDivRow {
            get {
                return ResourceManager.GetString("OpenDivRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;.
        /// </summary>
        internal static string OpenH3 {
            get {
                return ResourceManager.GetString("OpenH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th&gt;.
        /// </summary>
        internal static string OpenTh {
            get {
                return ResourceManager.GetString("OpenTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string OpenTr {
            get {
                return ResourceManager.GetString("OpenTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string PorcentajeCompleto {
            get {
                return ResourceManager.GetString("PorcentajeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PorcentajeRealizado:.
        /// </summary>
        internal static string PorcentajeDeRealizacion {
            get {
                return ResourceManager.GetString("PorcentajeDeRealizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propuesta:.
        /// </summary>
        internal static string PropuestaAprovada {
            get {
                return ResourceManager.GetString("PropuestaAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../M8/GenerarFacturaM8.aspx?IdCompania=.
        /// </summary>
        internal static string RedirectFactura {
            get {
                return ResourceManager.GetString("RedirectFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../M7/InformacionProyecto.aspx?idCont=.
        /// </summary>
        internal static string RedirectInfoProyecto {
            get {
                return ResourceManager.GetString("RedirectInfoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string tipoAlerta {
            get {
                return ResourceManager.GetString("tipoAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
