//------------------------------------------------------------------------------
<<<<<<< HEAD
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
=======
// <generado automáticamente>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código. 
// </generado automáticamente>
>>>>>>> origin/master
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M4 {
    
    
    public partial class ConsultarCompania {
    }
}
