//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M4 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM4() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M4.ResourceGUIM4", typeof(ResourceGUIM4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acrónimo:.
        /// </summary>
        internal static string Acronimo {
            get {
                return ResourceManager.GetString("Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Contactos&quot; class=&quot;btn btn-warning glyphicon glyphicon-list-alt&quot; style=&quot;margin-left: 3px&quot;  href=&quot;../M5/ConsultarContactos.aspx?typeComp=1&amp;idComp=.
        /// </summary>
        internal static string BotonContac {
            get {
                return ResourceManager.GetString("BotonContac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Involucrados&quot; class=&quot;btn btn-info glyphicon glyphicon-user&quot; style=&quot;margin-left: 3px&quot;  href=&quot;../M5/ConsultarContactos.aspx?typeComp=1&amp;idComp=.
        /// </summary>
        internal static string BotonInvol {
            get {
                return ResourceManager.GetString("BotonInvol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBoton {
            get {
                return ResourceManager.GetString("CloseBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonParametro {
            get {
                return ResourceManager.GetString("CloseBotonParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/div&gt;.
        /// </summary>
        internal static string CloseDiv {
            get {
                return ResourceManager.GetString("CloseDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/h3&gt;.
        /// </summary>
        internal static string Closeh3 {
            get {
                return ResourceManager.GetString("Closeh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/h4&gt;.
        /// </summary>
        internal static string Closeh4 {
            get {
                return ResourceManager.GetString("Closeh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ).
        /// </summary>
        internal static string CloseParentesis {
            get {
                return ResourceManager.GetString("CloseParentesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;Habilitada&lt;/span&gt;.
        /// </summary>
        internal static string CloseSpanHab {
            get {
                return ResourceManager.GetString("CloseSpanHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;Inhabilitada&lt;/span&gt;.
        /// </summary>
        internal static string CloseSpanInhab {
            get {
                return ResourceManager.GetString("CloseSpanInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CloseTD {
            get {
                return ResourceManager.GetString("CloseTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTR {
            get {
                return ResourceManager.GetString("CloseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comp.
        /// </summary>
        internal static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;span class=&quot;label label-success&quot; =&quot;h.
        /// </summary>
        internal static string habilitado {
            get {
                return ResourceManager.GetString("habilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;span class=&quot;label label-danger&quot; id=&quot;i.
        /// </summary>
        internal static string inhabilitado {
            get {
                return ResourceManager.GetString("inhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar:.
        /// </summary>
        internal static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Modificar&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; style=&quot;margin-left:3px;&quot; href=&quot;ModificarCompania.aspx?idComp=.
        /// </summary>
        internal static string OpenBotonEdit {
            get {
                return ResourceManager.GetString("OpenBotonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Habilitar&quot;  class=&quot;btn btn-success glyphicon glyphicon-ok&quot; style=&quot;margin-left:3px;&quot; href=&quot;ConsultarCompania.aspx?typeHab=1&amp;idComp=.
        /// </summary>
        internal static string OpenBotonHab {
            get {
                return ResourceManager.GetString("OpenBotonHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; style=&quot;margin-left:3px;&quot;OnClick=&quot;MostrarInfo&quot;href=&quot;InformacionCompania.aspx?idComp=.
        /// </summary>
        internal static string OpenBotonInfo {
            get {
                return ResourceManager.GetString("OpenBotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Inhabilitar&quot; class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; style=&quot;margin-left:3px;&quot; href=&quot;ConsultarCompania.aspx?typeHab=0&amp;idComp=.
        /// </summary>
        internal static string OpenBotonInhab {
            get {
                return ResourceManager.GetString("OpenBotonInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;center-block&quot;&gt;.
        /// </summary>
        internal static string OpenDivRow {
            get {
                return ResourceManager.GetString("OpenDivRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h3 style=&quot;bold&quot;&gt;.
        /// </summary>
        internal static string Openh3 {
            get {
                return ResourceManager.GetString("Openh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h4&gt;.
        /// </summary>
        internal static string Openh4 {
            get {
                return ResourceManager.GetString("Openh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (.
        /// </summary>
        internal static string OpenParentesis {
            get {
                return ResourceManager.GetString("OpenParentesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string OpenTR {
            get {
                return ResourceManager.GetString("OpenTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIF:.
        /// </summary>
        internal static string Rif {
            get {
                return ResourceManager.GetString("Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
    }
}
