//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M4 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM4() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M4.ResourceGUIM4", typeof(ResourceGUIM4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrónimo:.
        /// </summary>
        internal static string Acronimo {
            get {
                return ResourceManager.GetString("Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Contactos&quot; class=&quot;btn btn-warning glyphicon glyphicon-list-alt&quot; style=&quot;margin-left: 3px&quot;  href=&quot;../M5/ConsultarContactos.aspx?typeComp=1&amp;idComp=.
        /// </summary>
        internal static string BotonContac {
            get {
                return ResourceManager.GetString("BotonContac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Administrar Contactos&quot; class=&quot;btn btn-info glyphicon glyphicon-user&quot; style=&quot;margin-left: 3px&quot;  href=&quot;../M5/ConsultarContactos.aspx?typeComp=1&amp;idComp=.
        /// </summary>
        internal static string BotonInvol {
            get {
                return ResourceManager.GetString("BotonInvol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBoton {
            get {
                return ResourceManager.GetString("CloseBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonParametro {
            get {
                return ResourceManager.GetString("CloseBotonParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string CloseDiv {
            get {
                return ResourceManager.GetString("CloseDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h3&gt;.
        /// </summary>
        internal static string Closeh3 {
            get {
                return ResourceManager.GetString("Closeh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h4&gt;.
        /// </summary>
        internal static string Closeh4 {
            get {
                return ResourceManager.GetString("Closeh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string CloseParentesis {
            get {
                return ResourceManager.GetString("CloseParentesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;Habilitada&lt;/span&gt;.
        /// </summary>
        internal static string CloseSpanHab {
            get {
                return ResourceManager.GetString("CloseSpanHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;Inhabilitada&lt;/span&gt;.
        /// </summary>
        internal static string CloseSpanInhab {
            get {
                return ResourceManager.GetString("CloseSpanInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CloseTD {
            get {
                return ResourceManager.GetString("CloseTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTR {
            get {
                return ResourceManager.GetString("CloseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp.
        /// </summary>
        internal static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dìas..
        /// </summary>
        internal static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha:.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-success&quot; =&quot;h.
        /// </summary>
        internal static string habilitado {
            get {
                return ResourceManager.GetString("habilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-danger&quot; id=&quot;i.
        /// </summary>
        internal static string inhabilitado {
            get {
                return ResourceManager.GetString("inhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar:.
        /// </summary>
        internal static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Modificar&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; style=&quot;margin-left:3px;&quot; href=&quot;ModificarCompania.aspx?idComp=.
        /// </summary>
        internal static string OpenBotonEdit {
            get {
                return ResourceManager.GetString("OpenBotonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Habilitar&quot;  class=&quot;btn btn-success glyphicon glyphicon-ok&quot; style=&quot;margin-left:3px;&quot; href=&quot;ConsultarCompania.aspx?typeHab=1&amp;idComp=.
        /// </summary>
        internal static string OpenBotonHab {
            get {
                return ResourceManager.GetString("OpenBotonHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; style=&quot;margin-left:3px;&quot;OnClick=&quot;MostrarInfo&quot;href=&quot;InformacionCompania.aspx?idComp=.
        /// </summary>
        internal static string OpenBotonInfo {
            get {
                return ResourceManager.GetString("OpenBotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a title=&quot;Inhabilitar&quot; class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; style=&quot;margin-left:3px;&quot; href=&quot;ConsultarCompania.aspx?typeHab=0&amp;idComp=.
        /// </summary>
        internal static string OpenBotonInhab {
            get {
                return ResourceManager.GetString("OpenBotonInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;center-block&quot;&gt;.
        /// </summary>
        internal static string OpenDivRow {
            get {
                return ResourceManager.GetString("OpenDivRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 style=&quot;bold&quot;&gt;.
        /// </summary>
        internal static string Openh3 {
            get {
                return ResourceManager.GetString("Openh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;.
        /// </summary>
        internal static string Openh4 {
            get {
                return ResourceManager.GetString("Openh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string OpenParentesis {
            get {
                return ResourceManager.GetString("OpenParentesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string OpenTR {
            get {
                return ResourceManager.GetString("OpenTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo de Pagos:.
        /// </summary>
        internal static string PlazoPago {
            get {
                return ResourceManager.GetString("PlazoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto Actual:.
        /// </summary>
        internal static string Presupuesto {
            get {
                return ResourceManager.GetString("Presupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIF:.
        /// </summary>
        internal static string Rif {
            get {
                return ResourceManager.GetString("Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
