//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M4 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM4() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M4.ResourceGUIM4", typeof(ResourceGUIM4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Contactos&quot; class=&quot;btn btn-warning glyphicon glyphicon-list-alt&quot; &gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonContac {
            get {
                return ResourceManager.GetString("BotonContac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Habilitar&quot;  class=&quot;btn btn-success glyphicon glyphicon-ok&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonHab {
            get {
                return ResourceManager.GetString("BotonHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInfo {
            get {
                return ResourceManager.GetString("BotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Inhabilitar&quot; class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; &gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInhab {
            get {
                return ResourceManager.GetString("BotonInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Involucrados&quot; class=&quot;btn btn-info glyphicon glyphicon-user&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonInvol {
            get {
                return ResourceManager.GetString("BotonInvol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Modificar&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModalE&quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonModif {
            get {
                return ResourceManager.GetString("BotonModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBoton {
            get {
                return ResourceManager.GetString("CloseBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonParametro {
            get {
                return ResourceManager.GetString("CloseBotonParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CloseTD {
            get {
                return ResourceManager.GetString("CloseTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTR {
            get {
                return ResourceManager.GetString("CloseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ,.
        /// </summary>
        internal static string Coma {
            get {
                return ResourceManager.GetString("Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comp.
        /// </summary>
        internal static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;span class=&quot;label label-success&quot;&gt;Habilitada&lt;/span&gt;.
        /// </summary>
        internal static string habilitado {
            get {
                return ResourceManager.GetString("habilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;span class=&quot;label label-danger&quot;&gt;Inhabilitada&lt;/span&gt;.
        /// </summary>
        internal static string inhabilitado {
            get {
                return ResourceManager.GetString("inhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Modificar&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; style=&quot;margin-left 0.2px&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModalE&quot; id=&quot;Edi.
        /// </summary>
        internal static string OpenBotonEdit {
            get {
                return ResourceManager.GetString("OpenBotonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Habilitar&quot;  class=&quot;btn btn-success glyphicon glyphicon-ok&quot; style=&quot;margin-left 0.2px&quot; id=&quot;Hab.
        /// </summary>
        internal static string OpenBotonHab {
            get {
                return ResourceManager.GetString("OpenBotonHab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Informacion&quot; class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; style=&quot;margin-left 0.2px&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot; OnClick=&quot;MostrarInfo&quot; id=&quot;Inf.
        /// </summary>
        internal static string OpenBotonInfo {
            get {
                return ResourceManager.GetString("OpenBotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Inhabilitar&quot; class=&quot;btn btn-danger glyphicon glyphicon-remove&quot; style=&quot;margin-left 0.2px&quot; id=&quot;Inh.
        /// </summary>
        internal static string OpenBotonInhab {
            get {
                return ResourceManager.GetString("OpenBotonInhab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string OpenTR {
            get {
                return ResourceManager.GetString("OpenTR", resourceCulture);
            }
        }
    }
}
