//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTangerine.M7 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceProyecto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceProyecto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTangerine.M7.ResourceProyecto", typeof(ResourceProyecto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_AgregarProyecto.
        /// </summary>
        internal static string AddNewProyecto {
            get {
                return ResourceManager.GetString("AddNewProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_AgregarProyectoContacto.
        /// </summary>
        internal static string AddNewProyectoContacto {
            get {
                return ResourceManager.GetString("AddNewProyectoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_AgregarProyectoEmpleado.
        /// </summary>
        internal static string AddProyectoEmpleado {
            get {
                return ResourceManager.GetString("AddProyectoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ModificarProyecto.
        /// </summary>
        internal static string ChangeProyecto {
            get {
                return ResourceManager.GetString("ChangeProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarNombrePropuestaID.
        /// </summary>
        internal static string ContactNombrePropuestaID {
            get {
                return ResourceManager.GetString("ContactNombrePropuestaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarProyecto.
        /// </summary>
        internal static string ContactProyecto {
            get {
                return ResourceManager.GetString("ContactProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarProyectoContacto.
        /// </summary>
        internal static string ContactProyectoContacto {
            get {
                return ResourceManager.GetString("ContactProyectoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarProyectoEmpleado.
        /// </summary>
        internal static string ContactProyectoEmpleado {
            get {
                return ResourceManager.GetString("ContactProyectoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarProyectoTrabajaEmpleado.
        /// </summary>
        internal static string ContactProyectoPorEmpleado {
            get {
                return ResourceManager.GetString("ContactProyectoPorEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarProyectosPorGerente.
        /// </summary>
        internal static string ContactProyectoPorGerente {
            get {
                return ResourceManager.GetString("ContactProyectoPorGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarProyectos.
        /// </summary>
        internal static string ContactProyectos {
            get {
                return ResourceManager.GetString("ContactProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarAcuerdoPagoMensual.
        /// </summary>
        internal static string ContactProyectosxAcuerdoPago {
            get {
                return ResourceManager.GetString("ContactProyectosxAcuerdoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_EliminarProyecto.
        /// </summary>
        internal static string DeleteProyecto {
            get {
                return ResourceManager.GetString("DeleteProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_EliminarProyectoContacto.
        /// </summary>
        internal static string DeleteProyectoContacto {
            get {
                return ResourceManager.GetString("DeleteProyectoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_EliminarProyectoEmpleado.
        /// </summary>
        internal static string DeleteProyectoEmpleado {
            get {
                return ResourceManager.GetString("DeleteProyectoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @AcuerdoPago.
        /// </summary>
        internal static string ParamAcuerdoPago {
            get {
                return ResourceManager.GetString("ParamAcuerdoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Codigo.
        /// </summary>
        internal static string ParamCodigo {
            get {
                return ResourceManager.GetString("ParamCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Costo.
        /// </summary>
        internal static string ParamCosto {
            get {
                return ResourceManager.GetString("ParamCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Descripcion.
        /// </summary>
        internal static string ParamDescripcion {
            get {
                return ResourceManager.GetString("ParamDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Estatus.
        /// </summary>
        internal static string ParamEstatus {
            get {
                return ResourceManager.GetString("ParamEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @FechaEstFin.
        /// </summary>
        internal static string ParamFechaEstFin {
            get {
                return ResourceManager.GetString("ParamFechaEstFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @FechaInicio.
        /// </summary>
        internal static string ParamFechaInicio {
            get {
                return ResourceManager.GetString("ParamFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdProyecto.
        /// </summary>
        internal static string ParamId_Proyecto {
            get {
                return ResourceManager.GetString("ParamId_Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdCompania.
        /// </summary>
        internal static string ParamIdCompania {
            get {
                return ResourceManager.GetString("ParamIdCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdGerente.
        /// </summary>
        internal static string ParamIdGerente {
            get {
                return ResourceManager.GetString("ParamIdGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdPropuesta.
        /// </summary>
        internal static string ParamIdPropuesta {
            get {
                return ResourceManager.GetString("ParamIdPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdPropuestaPrpu.
        /// </summary>
        internal static string ParamIdPropuestaPrpu {
            get {
                return ResourceManager.GetString("ParamIdPropuestaPrpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Nombre.
        /// </summary>
        internal static string ParamNombre {
            get {
                return ResourceManager.GetString("ParamNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @PCIdContacto.
        /// </summary>
        internal static string ParamPCIdContacto {
            get {
                return ResourceManager.GetString("ParamPCIdContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @PEIdEmpleado.
        /// </summary>
        internal static string ParamPEIdEmpleado {
            get {
                return ResourceManager.GetString("ParamPEIdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Razon.
        /// </summary>
        internal static string ParamRazon {
            get {
                return ResourceManager.GetString("ParamRazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Realizacion.
        /// </summary>
        internal static string ParamRealizacion {
            get {
                return ResourceManager.GetString("ParamRealizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_con_id.
        /// </summary>
        internal static string PCIdContacto {
            get {
                return ResourceManager.GetString("PCIdContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_emp_num_ficha.
        /// </summary>
        internal static string PEIdEmpleado {
            get {
                return ResourceManager.GetString("PEIdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_acuerdo_pago.
        /// </summary>
        internal static string ProyAcuerdoPago {
            get {
                return ResourceManager.GetString("ProyAcuerdoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_codigo.
        /// </summary>
        internal static string ProyCodigo {
            get {
                return ResourceManager.GetString("ProyCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_costo.
        /// </summary>
        internal static string ProyCosto {
            get {
                return ResourceManager.GetString("ProyCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_descripcion.
        /// </summary>
        internal static string ProyDescripcion {
            get {
                return ResourceManager.GetString("ProyDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_estatus.
        /// </summary>
        internal static string ProyEstatus {
            get {
                return ResourceManager.GetString("ProyEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_fecha_est_fin.
        /// </summary>
        internal static string ProyFechaEstFin {
            get {
                return ResourceManager.GetString("ProyFechaEstFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_fecha_inicio.
        /// </summary>
        internal static string ProyFechaInicio {
            get {
                return ResourceManager.GetString("ProyFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_com_id.
        /// </summary>
        internal static string ProyIdCompania {
            get {
                return ResourceManager.GetString("ProyIdCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_gerente_id.
        /// </summary>
        internal static string ProyIdGerente {
            get {
                return ResourceManager.GetString("ProyIdGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_propuesta_id.
        /// </summary>
        internal static string ProyIdPropuesta {
            get {
                return ResourceManager.GetString("ProyIdPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_id.
        /// </summary>
        internal static string ProyIdProyecto {
            get {
                return ResourceManager.GetString("ProyIdProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_nombre.
        /// </summary>
        internal static string ProyNombre {
            get {
                return ResourceManager.GetString("ProyNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_razon.
        /// </summary>
        internal static string ProyRazon {
            get {
                return ResourceManager.GetString("ProyRazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proy_realizacion.
        /// </summary>
        internal static string ProyRealizacion {
            get {
                return ResourceManager.GetString("ProyRealizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a prop_nombre.
        /// </summary>
        internal static string PrpuNombre {
            get {
                return ResourceManager.GetString("PrpuNombre", resourceCulture);
            }
        }
    }
}
