//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM5() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M5.ResourceGUIM5", typeof(ResourceGUIM5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string AbrirTD {
            get {
                return ResourceManager.GetString("AbrirTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string AbrirTR {
            get {
                return ResourceManager.GetString("AbrirTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string alertaError {
            get {
                return ResourceManager.GetString("alertaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string alertaHtml {
            get {
                return ResourceManager.GetString("alertaHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string alertaHtmlFinal {
            get {
                return ResourceManager.GetString("alertaHtmlFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-dismissible.
        /// </summary>
        internal static string alertaSuccess {
            get {
                return ResourceManager.GetString("alertaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string alertClase1 {
            get {
                return ResourceManager.GetString("alertClase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string alertRole1 {
            get {
                return ResourceManager.GetString("alertRole1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;make-switch switch-mini&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-switch&quot; &gt;
        ///                            &lt;input type=&quot;checkbox&quot; data-toggle=&quot;toggle&quot; data-on=&quot;ON&quot; data-off=&quot;OFF &quot;checked id=&quot;.
        /// </summary>
        internal static string BotonActivarPlanilla {
            get {
                return ResourceManager.GetString("BotonActivarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonCerrar1 {
            get {
                return ResourceManager.GetString("BotonCerrar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;make-switch switch-mini&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-switch&quot; &gt;
        ///                            &lt;input type=&quot;checkbox&quot; data-toggle=&quot;toggle&quot; data-on=&quot;ON&quot; data-off=&quot;OFF &quot; id=&quot;.
        /// </summary>
        internal static string BotonDesactivarPlanilla {
            get {
                return ResourceManager.GetString("BotonDesactivarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  class=&quot;btn btn-danger glyphicon glyphicon-remove-circle&quot; href=&quot;M14_ConsultarPlanillasSolicitadas.aspx?idEliminar=.
        /// </summary>
        internal static string BotonEliminarSolicitud {
            get {
                return ResourceManager.GetString("BotonEliminarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;.
        /// </summary>
        internal static string BotonInfo {
            get {
                return ResourceManager.GetString("BotonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; href=&quot;M14_ConsultarPlanillasSolicitadas.aspx?idSolici=.
        /// </summary>
        internal static string BotonInfoSolicitud {
            get {
                return ResourceManager.GetString("BotonInfoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  class=&quot;btn btn-primary&quot; href=&quot;M14_SolicitudPlanilla.aspx?idPlan=.
        /// </summary>
        internal static string BotonSolicitarPlanilla {
            get {
                return ResourceManager.GetString("BotonSolicitarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  class=&quot;btn btn-default glyphicon glyphicon-pencil&quot; href=&quot;ModificarContacto.aspx?idCont=.
        /// </summary>
        internal static string ButtonModContact {
            get {
                return ResourceManager.GetString("ButtonModContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen campos vacios, todos los campos son obligatorios.
        /// </summary>
        internal static string camposVacios {
            get {
                return ResourceManager.GetString("camposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;Solicitar&lt;/a&gt;.
        /// </summary>
        internal static string CerrarSolicitud {
            get {
                return ResourceManager.GetString("CerrarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CerrarTD {
            get {
                return ResourceManager.GetString("CerrarTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarTR {
            get {
                return ResourceManager.GetString("CerrarTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Coma {
            get {
                return ResourceManager.GetString("Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emax.
        /// </summary>
        internal static string emax {
            get {
                return ResourceManager.GetString("emax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emin.
        /// </summary>
        internal static string emin {
            get {
                return ResourceManager.GetString("emin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPlan.
        /// </summary>
        internal static string idP {
            get {
                return ResourceManager.GetString("idP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPlan.
        /// </summary>
        internal static string IdPlan {
            get {
                return ResourceManager.GetString("IdPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.3.
        /// </summary>
        internal static string interfazRCi {
            get {
                return ResourceManager.GetString("interfazRCi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1.
        /// </summary>
        internal static string interfazRH {
            get {
                return ResourceManager.GetString("interfazRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Mod8 {
            get {
                return ResourceManager.GetString("Mod8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Modulo8/interfazRestriccionesAvanceCinta.aspx?succes=true.
        /// </summary>
        internal static string ReturnRestCinta {
            get {
                return ResourceManager.GetString("ReturnRestCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sexo.
        /// </summary>
        internal static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stat.
        /// </summary>
        internal static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stat.
        /// </summary>
        internal static string statrec {
            get {
                return ResourceManager.GetString("statrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string tipoAlerta {
            get {
                return ResourceManager.GetString("tipoAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Modulo8/interfazRestriccionesHorario.aspx?stat=.
        /// </summary>
        internal static string volverRestriccionHorario {
            get {
                return ResourceManager.GetString("volverRestriccionHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Modulo8/interfazRestriccionesHorario.aspx?idPlan=.
        /// </summary>
        internal static string volverRestriccionHorario2 {
            get {
                return ResourceManager.GetString("volverRestriccionHorario2", resourceCulture);
            }
        }
    }
}
