//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTangerine.M10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEmpleado {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEmpleado() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTangerine.M10.ResourceEmpleado", typeof(ResourceEmpleado).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M10_AgregarEmpleado.
        /// </summary>
        internal static string AddNewEmpleado {
            get {
                return ResourceManager.GetString("AddNewEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M10_ConsultarEmpleado.
        /// </summary>
        internal static string ConsultarEmpleado {
            get {
                return ResourceManager.GetString("ConsultarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M10_DetallarEmpleado.
        /// </summary>
        internal static string DetallarEmpleado {
            get {
                return ResourceManager.GetString("DetallarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_activo.
        /// </summary>
        internal static string EmpActivo {
            get {
                return ResourceManager.GetString("EmpActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_nombre.
        /// </summary>
        internal static string EmpCargo {
            get {
                return ResourceManager.GetString("EmpCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_descripcion.
        /// </summary>
        internal static string EmpCargoDescripcion {
            get {
                return ResourceManager.GetString("EmpCargoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_cedula.
        /// </summary>
        internal static string EmpCedula {
            get {
                return ResourceManager.GetString("EmpCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DireccionEmpleado.
        /// </summary>
        internal static string EmpDireccion {
            get {
                return ResourceManager.GetString("EmpDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_email.
        /// </summary>
        internal static string EmpEmail {
            get {
                return ResourceManager.GetString("EmpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_nivel_estudio.
        /// </summary>
        internal static string EmpEstudio {
            get {
                return ResourceManager.GetString("EmpEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_fecha_nac.
        /// </summary>
        internal static string EmpFecha {
            get {
                return ResourceManager.GetString("EmpFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_emp_fecha_fin.
        /// </summary>
        internal static string EmpFechaFin {
            get {
                return ResourceManager.GetString("EmpFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_emp_fecha_cont.
        /// </summary>
        internal static string EmpFechaInicio {
            get {
                return ResourceManager.GetString("EmpFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_genero.
        /// </summary>
        internal static string EmpGenero {
            get {
                return ResourceManager.GetString("EmpGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_num_ficha.
        /// </summary>
        internal static string EmpIdEmpleado {
            get {
                return ResourceManager.GetString("EmpIdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_lug_dir_id.
        /// </summary>
        internal static string EmpLugId {
            get {
                return ResourceManager.GetString("EmpLugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_p_apellido.
        /// </summary>
        internal static string EmpPApellido {
            get {
                return ResourceManager.GetString("EmpPApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_p_nombre.
        /// </summary>
        internal static string EmpPNombre {
            get {
                return ResourceManager.GetString("EmpPNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_s_apellido.
        /// </summary>
        internal static string EmpSApellido {
            get {
                return ResourceManager.GetString("EmpSApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_s_nombre.
        /// </summary>
        internal static string EmpSNombre {
            get {
                return ResourceManager.GetString("EmpSNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_emp_sueldo.
        /// </summary>
        internal static string EmpSueldo {
            get {
                return ResourceManager.GetString("EmpSueldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @activo.
        /// </summary>
        internal static string ParamActivo {
            get {
                return ResourceManager.GetString("ParamActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cedula.
        /// </summary>
        internal static string ParamCedula {
            get {
                return ResourceManager.GetString("ParamCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @prueba.
        /// </summary>
        internal static string ParamCPrueba {
            get {
                return ResourceManager.GetString("ParamCPrueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @direccion.
        /// </summary>
        internal static string ParamDireccion {
            get {
                return ResourceManager.GetString("ParamDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        internal static string ParamEmail {
            get {
                return ResourceManager.GetString("ParamEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @estado.
        /// </summary>
        internal static string ParamEstado {
            get {
                return ResourceManager.GetString("ParamEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_nac.
        /// </summary>
        internal static string ParamFechaNac {
            get {
                return ResourceManager.GetString("ParamFechaNac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ficha.
        /// </summary>
        internal static string ParamFicha {
            get {
                return ResourceManager.GetString("ParamFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @genero.
        /// </summary>
        internal static string ParamGenero {
            get {
                return ResourceManager.GetString("ParamGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nivel_estudio.
        /// </summary>
        internal static string ParamNivelEstudio {
            get {
                return ResourceManager.GetString("ParamNivelEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pais.
        /// </summary>
        internal static string ParamPais {
            get {
                return ResourceManager.GetString("ParamPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_apellido.
        /// </summary>
        internal static string ParamPApellido {
            get {
                return ResourceManager.GetString("ParamPApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_nombre.
        /// </summary>
        internal static string ParamPNombre {
            get {
                return ResourceManager.GetString("ParamPNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @s_apellido.
        /// </summary>
        internal static string ParamSApellido {
            get {
                return ResourceManager.GetString("ParamSApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @s_nombre.
        /// </summary>
        internal static string ParamSNombre {
            get {
                return ResourceManager.GetString("ParamSNombre", resourceCulture);
            }
        }
    }
}
