//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTangerine.M5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceContact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceContact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTangerine.M5.ResourceContact", typeof(ResourceContact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_AgregarContacto.
        /// </summary>
        internal static string AddNewContact {
            get {
                return ResourceManager.GetString("AddNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_AgregarContactoProyecto.
        /// </summary>
        internal static string AddNewContactProy {
            get {
                return ResourceManager.GetString("AddNewContactProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ModificarContacto.
        /// </summary>
        internal static string ChangeContact {
            get {
                return ResourceManager.GetString("ChangeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGE_00_001.
        /// </summary>
        internal static string Codigo_Error_Formato {
            get {
                return ResourceManager.GetString("Codigo_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_departamento.
        /// </summary>
        internal static string ConDepartmentContact {
            get {
                return ResourceManager.GetString("ConDepartmentContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_correo.
        /// </summary>
        internal static string ConEmailContact {
            get {
                return ResourceManager.GetString("ConEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_id_com_lead.
        /// </summary>
        internal static string ConIdComp {
            get {
                return ResourceManager.GetString("ConIdComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_id.
        /// </summary>
        internal static string ConIdContact {
            get {
                return ResourceManager.GetString("ConIdContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_apellido.
        /// </summary>
        internal static string ConLastNameContact {
            get {
                return ResourceManager.GetString("ConLastNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_nombre.
        /// </summary>
        internal static string ConNameContact {
            get {
                return ResourceManager.GetString("ConNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_telefono.
        /// </summary>
        internal static string ConPhoneContact {
            get {
                return ResourceManager.GetString("ConPhoneContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_cargo.
        /// </summary>
        internal static string ConRolContact {
            get {
                return ResourceManager.GetString("ConRolContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarContactoCompania.
        /// </summary>
        internal static string ContactCompany {
            get {
                return ResourceManager.GetString("ContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_tipo_emp.
        /// </summary>
        internal static string ConTypeComp {
            get {
                return ResourceManager.GetString("ConTypeComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_EliminarContacto.
        /// </summary>
        internal static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string Mensaje_Error_Formato {
            get {
                return ResourceManager.GetString("Mensaje_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @departamento.
        /// </summary>
        internal static string ParamDepa {
            get {
                return ResourceManager.GetString("ParamDepa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @correo.
        /// </summary>
        internal static string ParamEmail {
            get {
                return ResourceManager.GetString("ParamEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string ParamId {
            get {
                return ResourceManager.GetString("ParamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_empresa.
        /// </summary>
        internal static string ParamIdComp {
            get {
                return ResourceManager.GetString("ParamIdComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_contacto.
        /// </summary>
        internal static string ParamIdContact {
            get {
                return ResourceManager.GetString("ParamIdContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_proyecto.
        /// </summary>
        internal static string ParamIdProy {
            get {
                return ResourceManager.GetString("ParamIdProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @apellido.
        /// </summary>
        internal static string ParamLName {
            get {
                return ResourceManager.GetString("ParamLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParamName {
            get {
                return ResourceManager.GetString("ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cargo.
        /// </summary>
        internal static string ParamRol {
            get {
                return ResourceManager.GetString("ParamRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipo_comp.
        /// </summary>
        internal static string ParamTComp {
            get {
                return ResourceManager.GetString("ParamTComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefono.
        /// </summary>
        internal static string ParamTele {
            get {
                return ResourceManager.GetString("ParamTele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarContactoId.
        /// </summary>
        internal static string SingleContact {
            get {
                return ResourceManager.GetString("SingleContact", resourceCulture);
            }
        }
    }
}
