//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTangerine.M8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFactura {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFactura() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTangerine.M8.ResourceFactura", typeof(ResourceFactura).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_AgregarFactura.
        /// </summary>
        internal static string AddNewFactura {
            get {
                return ResourceManager.GetString("AddNewFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_ModificarContacto.
        /// </summary>
        internal static string ChangeFactura {
            get {
                return ResourceManager.GetString("ChangeFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_ConsultarFactura.
        /// </summary>
        internal static string ContactFactura {
            get {
                return ResourceManager.GetString("ContactFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_EliminarFactura.
        /// </summary>
        internal static string DeleteFactura {
            get {
                return ResourceManager.GetString("DeleteFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fac_descripcion.
        /// </summary>
        internal static string FacDescripcion {
            get {
                return ResourceManager.GetString("FacDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fac_fecha_emision.
        /// </summary>
        internal static string FacFechaEmision {
            get {
                return ResourceManager.GetString("FacFechaEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_compania_id.
        /// </summary>
        internal static string FacIdCompania {
            get {
                return ResourceManager.GetString("FacIdCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fac_id.
        /// </summary>
        internal static string FacIdFactura {
            get {
                return ResourceManager.GetString("FacIdFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_proy_id.
        /// </summary>
        internal static string FacIdProyecto {
            get {
                return ResourceManager.GetString("FacIdProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fac_monto_restante.
        /// </summary>
        internal static string FacMontoRestante {
            get {
                return ResourceManager.GetString("FacMontoRestante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fac_monto_total.
        /// </summary>
        internal static string FacMontoTotal {
            get {
                return ResourceManager.GetString("FacMontoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @descripcion.
        /// </summary>
        internal static string ParamDescripcion {
            get {
                return ResourceManager.GetString("ParamDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha_emision.
        /// </summary>
        internal static string ParamFecha_Emision {
            get {
                return ResourceManager.GetString("ParamFecha_Emision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_compania.
        /// </summary>
        internal static string ParamIdCompania {
            get {
                return ResourceManager.GetString("ParamIdCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IdFactura.
        /// </summary>
        internal static string ParamIdFactura {
            get {
                return ResourceManager.GetString("ParamIdFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_proyecto.
        /// </summary>
        internal static string ParamIdProyecto {
            get {
                return ResourceManager.GetString("ParamIdProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @monto_restante.
        /// </summary>
        internal static string ParamMonto_Restante {
            get {
                return ResourceManager.GetString("ParamMonto_Restante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @monto_total.
        /// </summary>
        internal static string ParamMonto_Total {
            get {
                return ResourceManager.GetString("ParamMonto_Total", resourceCulture);
            }
        }
    }
}
