//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM10 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM10() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M1.ResourceGUIM10", typeof(ResourceGUIM10).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string AbrirTD {
            get {
                return ResourceManager.GetString("AbrirTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string AbrirTR {
            get {
                return ResourceManager.GetString("AbrirTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;ModificarEmpleado.aspx?idEmp=.
        /// </summary>
        internal static string BotonModificarEmpAbrir {
            get {
                return ResourceManager.GetString("BotonModificarEmpAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; type=&quot;button&quot; class=&quot;btn btn-default&quot;&gt;&lt;span class=&quot;glyphicon glyphicon-pencil&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonModificarEmpCerrar {
            get {
                return ResourceManager.GetString("BotonModificarEmpCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;ModificarEmpleado.aspx.
        /// </summary>
        internal static string BotonStatusEmpAbrir {
            get {
                return ResourceManager.GetString("BotonStatusEmpAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; type=&quot;button&quot; class=&quot;btn btn-danger&quot;&gt;&lt;span class=&quot;glyphicon glyphicon-remove-circle&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonStatusEmpCerrar {
            get {
                return ResourceManager.GetString("BotonStatusEmpCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;VerEmpleado.aspx?idEmp=.
        /// </summary>
        internal static string BotonVerEmpAbrir {
            get {
                return ResourceManager.GetString("BotonVerEmpAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; type=&quot;button&quot; class=&quot;btn btn-primary&quot;&gt;&lt;span class=&quot;glyphicon glyphicon-search&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonVerEmpCerrar {
            get {
                return ResourceManager.GetString("BotonVerEmpCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CerrarTD {
            get {
                return ResourceManager.GetString("CerrarTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarTR {
            get {
                return ResourceManager.GetString("CerrarTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  .
        /// </summary>
        internal static string Espacio {
            get {
                return ResourceManager.GetString("Espacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        internal static string FormatoFecha {
            get {
                return ResourceManager.GetString("FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;CrearEmpleado.aspx&quot; type=&quot;button&quot; class=&quot;btn btn-success pull-right&quot;&gt;&lt;span class=&quot;glyphicon glyphicon-plus&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string VentanaAgregarEmpleado {
            get {
                return ResourceManager.GetString("VentanaAgregarEmpleado", resourceCulture);
            }
        }
    }
}
