//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine_Presentador.M5 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoM5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoM5() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine_Presentador.M5.RecursoM5", typeof(RecursoM5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string AbrirTD {
            get {
                return ResourceManager.GetString("AbrirTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td style=&quot;text-align:center;&quot;&gt;.
        /// </summary>
        internal static string AbrirTD2 {
            get {
                return ResourceManager.GetString("AbrirTD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string AbrirTR {
            get {
                return ResourceManager.GetString("AbrirTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-danger alert-dismissible.
        /// </summary>
        internal static string AlertDanger {
            get {
                return ResourceManager.GetString("AlertDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string AlertShowSu1 {
            get {
                return ResourceManager.GetString("AlertShowSu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/div&gt;.
        /// </summary>
        internal static string AlertShowSu2 {
            get {
                return ResourceManager.GetString("AlertShowSu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-success alert-dismissible.
        /// </summary>
        internal static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Eliminar Contacto&quot; class=&quot;btn btn-danger glyphicon glyphicon-trash&quot; style=&quot;margin-left:3px;&quot; href=&quot;ConsultarContactos.aspx?typeComp=.
        /// </summary>
        internal static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;idCont=.
        /// </summary>
        internal static string BotonEliminar2 {
            get {
                return ResourceManager.GetString("BotonEliminar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;idComp=.
        /// </summary>
        internal static string BotonVolver2 {
            get {
                return ResourceManager.GetString("BotonVolver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;status=.
        /// </summary>
        internal static string BotonVolver4 {
            get {
                return ResourceManager.GetString("BotonVolver4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&quot;Modificar Contacto&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; style=&quot;margin-left:3px;&quot; href=&quot;ModificarContacto.aspx?typeComp=.
        /// </summary>
        internal static string ButtonModContact {
            get {
                return ResourceManager.GetString("ButtonModContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CerrarTD {
            get {
                return ResourceManager.GetString("CerrarTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarTR {
            get {
                return ResourceManager.GetString("CerrarTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ,.
        /// </summary>
        internal static string Coma {
            get {
                return ResourceManager.GetString("Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía: .
        /// </summary>
        internal static string Compania {
            get {
                return ResourceManager.GetString("Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contacto ha sido creado correctamente.
        /// </summary>
        internal static string ContactoAgregado {
            get {
                return ResourceManager.GetString("ContactoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contacto ha sido eliminado correctamente.
        /// </summary>
        internal static string ContactoEliminado {
            get {
                return ResourceManager.GetString("ContactoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contacto ha sido modificado correctamente.
        /// </summary>
        internal static string ContactoModificado {
            get {
                return ResourceManager.GetString("ContactoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la base de datos, por favor intente de nuevo..
        /// </summary>
        internal static string ErrorBaseDeDatos {
            get {
                return ResourceManager.GetString("ErrorBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar compania, por favor intente de nuevo..
        /// </summary>
        internal static string ErrorConsultarCompania {
            get {
                return ResourceManager.GetString("ErrorConsultarCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar contacto(s), por favor intente de nuevo..
        /// </summary>
        internal static string ErrorConsultarContacto {
            get {
                return ResourceManager.GetString("ErrorConsultarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el contacto, por favor intente de nuevo..
        /// </summary>
        internal static string ErrorEliminarContacto {
            get {
                return ResourceManager.GetString("ErrorEliminarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al insertar información en la tabla, por favor intente de nuevo..
        /// </summary>
        internal static string ErrorLlenarTabla {
            get {
                return ResourceManager.GetString("ErrorLlenarTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead: .
        /// </summary>
        internal static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string StatusAgregado {
            get {
                return ResourceManager.GetString("StatusAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string StatusEliminado {
            get {
                return ResourceManager.GetString("StatusEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string StatusModificado {
            get {
                return ResourceManager.GetString("StatusModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a id=&quot;btn-cancelar&quot; type=&quot;submit&quot; style=&quot;margin-bottom:20px; margin-top:20px; margin-right:5%; height:35px; width:120px;&quot; class=&quot;btn btn-default&quot; href=&quot;../M3/Listar.aspx&quot;&gt;Volver&lt;/a&gt;.
        /// </summary>
        internal static string VolverCliPotencial {
            get {
                return ResourceManager.GetString("VolverCliPotencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a id=&quot;btn-cancelar&quot; type=&quot;submit&quot; style=&quot;margin-bottom:20px; margin-top:20px; margin-right:5%; height:35px; width:120px;&quot; class=&quot;btn btn-default&quot; href=&quot;../M4/ConsultarCompania.aspx&quot;&gt;Volver&lt;/a&gt;.
        /// </summary>
        internal static string VolverCompania {
            get {
                return ResourceManager.GetString("VolverCompania", resourceCulture);
            }
        }
    }
}
