//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM2() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M2.ResourceGUIM2", typeof(ResourceGUIM2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;#&quot;  tittle=&quot;modificar&quot; runat =&quot;server&quot; class=&quot;btn btn-default btn-xs&quot;disabled&gt;&lt;span class=&quot;glyphicon glyphicon-pencil&quot; data-toggle=&quot;&quot; data-target=&quot;&quot; &gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string Botonblock {
            get {
                return ResourceManager.GetString("Botonblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a tittle=&quot;modificar&quot; class=&quot;btn btn-default btn-xs&quot; id=&quot;.
        /// </summary>
        internal static string BotonModif {
            get {
                return ResourceManager.GetString("BotonModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;javascript:ajaxRes()&quot; tittle =&quot;registrar&quot; runat =&quot;server&quot;  class=&quot;btn btn-default btn-xs&quot; &gt;&lt;span class=&quot;glyphicon glyphicon-plus&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonReg {
            get {
                return ResourceManager.GetString("BotonReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;#&quot;  tittle=&quot;modificar&quot; runat =&quot;server&quot; class=&quot;btn btn-default btn-xs&quot;disabled&gt;&lt;span span class=&quot;glyphicon glyphicon-plus&quot; data-toggle=&quot;&quot; data-target=&quot;&quot; &gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonRegBlock {
            get {
                return ResourceManager.GetString("BotonRegBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;span class=&quot;glyphicon glyphicon-pencil&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModalC&quot; onclick=&quot;ClickCambiar&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonModify {
            get {
                return ResourceManager.GetString("CloseBotonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;span class=&quot;glyphicon glyphicon-plus&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonReg {
            get {
                return ResourceManager.GetString("CloseBotonReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/div&gt;.
        /// </summary>
        internal static string CloseDiv {
            get {
                return ResourceManager.GetString("CloseDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/h3&gt;.
        /// </summary>
        internal static string Closeh3 {
            get {
                return ResourceManager.GetString("Closeh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/h4&gt;.
        /// </summary>
        internal static string Closeh4 {
            get {
                return ResourceManager.GetString("Closeh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; disabled&gt;.
        /// </summary>
        internal static string CloseInputModif {
            get {
                return ResourceManager.GetString("CloseInputModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; class=&quot;col-sm-2 control-label&quot;&gt;Usuario&lt;/label&gt;.
        /// </summary>
        internal static string CloseLabelFor {
            get {
                return ResourceManager.GetString("CloseLabelFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CloseTD {
            get {
                return ResourceManager.GetString("CloseTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTR {
            get {
                return ResourceManager.GetString("CloseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;label for=&quot;.
        /// </summary>
        internal static string LabelFor {
            get {
                return ResourceManager.GetString("LabelFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a href=&quot;javascript:ajaxRes()&quot;  tittle=&quot;modificar&quot; runat =&quot;server&quot; class=&quot;btn btn-default btn-xs&quot;&gt;&lt;span class=&quot;glyphicon glyphicon-pencil&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot; &gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string llamadoCompleto {
            get {
                return ResourceManager.GetString("llamadoCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-sm-10&quot;&gt;.
        /// </summary>
        internal static string OpenDivModif {
            get {
                return ResourceManager.GetString("OpenDivModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;row&quot;&gt;.
        /// </summary>
        internal static string OpenDivRow {
            get {
                return ResourceManager.GetString("OpenDivRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h3 style=&quot;bold&quot;&gt;.
        /// </summary>
        internal static string Openh3 {
            get {
                return ResourceManager.GetString("Openh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h4&gt;.
        /// </summary>
        internal static string Openh4 {
            get {
                return ResourceManager.GetString("Openh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;input type=&quot;email&quot; class=&quot;form-control&quot; id=&quot;.
        /// </summary>
        internal static string OpenInputModif {
            get {
                return ResourceManager.GetString("OpenInputModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string OpenTR {
            get {
                return ResourceManager.GetString("OpenTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a placeholder=&quot;.
        /// </summary>
        internal static string placeholder {
            get {
                return ResourceManager.GetString("placeholder", resourceCulture);
            }
        }
    }
}
