//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUIM2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUIM2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M2.ResourceGUIM2", typeof(ResourceGUIM2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apellido=.
        /// </summary>
        internal static string ApellidoEmpleado {
            get {
                return ResourceManager.GetString("ApellidoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#&quot;  tittle=&quot;Modificar&quot; runat =&quot;server&quot; class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; disabled.
        /// </summary>
        internal static string Botonblock {
            get {
                return ResourceManager.GetString("Botonblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a tittle=&quot;modificar&quot; class=&quot;btn btn-default btn-xs&quot; id=&quot;.
        /// </summary>
        internal static string BotonModif {
            get {
                return ResourceManager.GetString("BotonModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;javascript:ajaxRes()&quot; tittle =&quot;registrar&quot; runat =&quot;server&quot;  class=&quot;btn btn-success btn-xs&quot; &gt;&lt;span class=&quot;glyphicon glyphicon-plus&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonReg {
            get {
                return ResourceManager.GetString("BotonReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  tittle=&quot;Asignar&quot; runat =&quot;server&quot;class=&quot;btn btn-success glyphicon glyphicon-plus&quot; disabled.
        /// </summary>
        internal static string BotonRegBlock {
            get {
                return ResourceManager.GetString("BotonRegBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  tittle=&quot;Asignar&quot; runat =&quot;server&quot;class=&quot;btn btn-success glyphicon glyphicon-plus&quot; href=&quot;AccionRegistrar.aspx?idFicha=.
        /// </summary>
        internal static string BotonRegNuevaVentana {
            get {
                return ResourceManager.GetString("BotonRegNuevaVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;span class=&quot;glyphicon glyphicon-pencil&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModalC&quot; onclick=&quot;ClickCambiar&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonModify {
            get {
                return ResourceManager.GetString("CloseBotonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonParametro {
            get {
                return ResourceManager.GetString("CloseBotonParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonParametroDesactivado {
            get {
                return ResourceManager.GetString("CloseBotonParametroDesactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;span class=&quot;glyphicon glyphicon-plus&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CloseBotonReg {
            get {
                return ResourceManager.GetString("CloseBotonReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string CloseDiv {
            get {
                return ResourceManager.GetString("CloseDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h3&gt;.
        /// </summary>
        internal static string Closeh3 {
            get {
                return ResourceManager.GetString("Closeh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h4&gt;.
        /// </summary>
        internal static string Closeh4 {
            get {
                return ResourceManager.GetString("Closeh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; disabled&gt;.
        /// </summary>
        internal static string CloseInputModif {
            get {
                return ResourceManager.GetString("CloseInputModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; class=&quot;col-sm-2 control-label&quot;&gt;Usuario&lt;/label&gt;.
        /// </summary>
        internal static string CloseLabelFor {
            get {
                return ResourceManager.GetString("CloseLabelFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CloseTD {
            get {
                return ResourceManager.GetString("CloseTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CloseTR {
            get {
                return ResourceManager.GetString("CloseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string comillas {
            get {
                return ResourceManager.GetString("comillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label for=&quot;.
        /// </summary>
        internal static string LabelFor {
            get {
                return ResourceManager.GetString("LabelFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;javascript:ajaxRes()&quot;  tittle=&quot;modificar&quot; runat =&quot;server&quot; class=&quot;btn btn-primary btn-xs&quot;&gt;&lt;span class=&quot;glyphicon glyphicon-pencil&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot; &gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string llamadoCompleto {
            get {
                return ResourceManager.GetString("llamadoCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  tittle=&quot;Asignar&quot; runat =&quot;server&quot;class=&quot;btn btn-primary glyphicon glyphicon-pencil&quot; href=&quot;AsignarRol.aspx?idEmpleado= .
        /// </summary>
        internal static string llamadoNuevaPagina {
            get {
                return ResourceManager.GetString("llamadoNuevaPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nombre=.
        /// </summary>
        internal static string NombreEmpleado {
            get {
                return ResourceManager.GetString("NombreEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;col-sm-10&quot;&gt;.
        /// </summary>
        internal static string OpenDivModif {
            get {
                return ResourceManager.GetString("OpenDivModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;.
        /// </summary>
        internal static string OpenDivRow {
            get {
                return ResourceManager.GetString("OpenDivRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 style=&quot;bold&quot;&gt;.
        /// </summary>
        internal static string Openh3 {
            get {
                return ResourceManager.GetString("Openh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;.
        /// </summary>
        internal static string Openh4 {
            get {
                return ResourceManager.GetString("Openh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;email&quot; class=&quot;form-control&quot; id=&quot;.
        /// </summary>
        internal static string OpenInputModif {
            get {
                return ResourceManager.GetString("OpenInputModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string OpenTD {
            get {
                return ResourceManager.GetString("OpenTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string OpenTR {
            get {
                return ResourceManager.GetString("OpenTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placeholder=&quot;.
        /// </summary>
        internal static string placeholder {
            get {
                return ResourceManager.GetString("placeholder", resourceCulture);
            }
        }
    }
}
