//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangerine.GUI.M2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceM2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceM2() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tangerine.GUI.M2.ResourceM2", typeof(ResourceM2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en datos, por favor, intente otra vez..
        /// </summary>
        internal static string AlertaBtnAsignar {
            get {
                return ResourceManager.GetString("AlertaBtnAsignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario ya existente, intente otro..
        /// </summary>
        internal static string AlertaBtnCrear {
            get {
                return ResourceManager.GetString("AlertaBtnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a class.
        /// </summary>
        internal static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a role.
        /// </summary>
        internal static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user.
        /// </summary>
        internal static string alertUsuario {
            get {
                return ResourceManager.GetString("alertUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idEmpleado.
        /// </summary>
        internal static string IDEmpleado {
            get {
                return ResourceManager.GetString("IDEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idFicha.
        /// </summary>
        internal static string IDFicha {
            get {
                return ResourceManager.GetString("IDFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../M2/CambiarRol.aspx?estado=1.
        /// </summary>
        internal static string RedirectBtnAsignarAsignarRol {
            get {
                return ResourceManager.GetString("RedirectBtnAsignarAsignarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../M2/CambiarRol.aspx?estado=2.
        /// </summary>
        internal static string RedirectBtnAsignarCambiarUsuario {
            get {
                return ResourceManager.GetString("RedirectBtnAsignarCambiarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../M2/RegistroUsuario.aspx?estado=1.
        /// </summary>
        internal static string RedirectBtnCrearAccionRegistar {
            get {
                return ResourceManager.GetString("RedirectBtnCrearAccionRegistar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../M1/DashBoard.aspx.
        /// </summary>
        internal static string RedirectPageLoad {
            get {
                return ResourceManager.GetString("RedirectPageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
    }
}
